name: Test CMSSW on plain docker
on:
  push:
    branches:
      - docker-04
  workflow_dispatch:

jobs:
  test_workflow:
    runs-on: ubuntu-latest
    name: DemoAnalyzer test - plain docker
    steps:
      # chmod of the script before getting to the container
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          mkdir outputs
      # run the container with the script in the repository
      - name: Going to a container
        id: container
        run: |
          docker run -v $(pwd):/mnt/vol -w /home/cmsusr cmsopendata/cmssw_7_6_7-slc6_amd64_gcc493 /bin/bash /mnt/vol/commands.sh
          echo ls -l  `ls -l `
          cp *.out outputs
      # upload output file
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: outputs/
